<?php
/**
 * Created by PhpStorm.
 * User: andi
 * Date: 16.11.14
 * Time: 22:41
 */

class ffapiTest extends PHPUnit_Framework_TestCase {
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }


    public function testGetValues()
    {
        $expected = array("kontakt@weimarnetz.de", "info@freifunk.net");
        $api = new ffapi("http://weimarnetz.de/ffapi/ffSummarizedDir.json");
        $results = $api->getValues("contact.email");
        assertEquals($results, $expected);
    }
}
 